[theme]
base = "light"          # or "dark"
primaryColor = "#2C6BED"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"     # options: "sans serif", "serif", or "monospace"

[server]
headless = true
port = 8501

